# app1/Dockerfile

# Utilise l'image officielle de Python
FROM python:3.9-slim

# Définit le répertoire de travail dans le conteneur
WORKDIR /app

# Copie le fichier de dépendances
COPY requirements.txt .

# Installe les dépendances
RUN pip install --no-cache-dir -r requirements.txt

# Copie le code de l'application
COPY . .

# Expose le port utilisé par l'application
EXPOSE 5000

# Définit la commande de lancement de l'application
CMD ["python", "app.py"]

